"""
Django settings for inmobiliaria project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from decouple import config
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
CONTRATOS_URL = '/contratos/'
CONTRATOS_ROOT = os.path.join(BASE_DIR, 'contratos')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-=ho1+m-e7v&em6l97swgu32rk78+xv8o2z+4vz@f0s#kkfjqe1'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*', '10.0.2.2', 'localhost', '192.168.0.10']
# ALLOWED_HOSTS = ['*']

AUTH_USER_MODEL = 'usuario.Usuario'

# Application definition


INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'rest_framework.authtoken',
    'usuario',
    'cita',
    'contrato',
    'inmueble',
    'contacto',
    'desempeno',
    'alertas',
    'reportes',
    'pago',
    'ventas',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    #'inmobiliaria.middleware.JsonErrorMiddleware'
]

ROOT_URLCONF = 'inmobiliaria.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# WSGI_APPLICATION = 'inmobiliaria.wsgi.application'
ASGI_APPLICATION = "inmobiliaria.asgi.application" #chat en tiempo real

#chat en tiempo real
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer",
    },
}

 #Database
#https://docs.djangoproject.com/en/5.2/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': config("DB_ENGINE", default="django.db.backends.postgresql"),
        'NAME': config("DB_NAME"),
        'USER': config("DB_USER"),
        'PASSWORD': config("DB_PASSWORD"),
        'HOST': config("DB_HOST", default="localhost"),
        'PORT': config("DB_PORT", default="5432"),
    }
}


# DATABASES = {
#     'default': {
#         'ENGINE': 'mssql',
#         'NAME': 'my-db',
#         'USER': '<admin-user>',
#         'PASSWORD': '<admin-password>',
#         'HOST': '<server-name>.database.windows.net',
#         'PORT': '',
#         'OPTIONS': {
#             'driver': 'ODBC Driver 17 for SQL Server',
#     },
# }
# }
# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    # {
    #     'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    # },
    # {
    #     'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    # },
    # {
    #     'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    # },
    # {
    #     'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    # },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/La_Paz'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://192.168.0.12:8000",
    "https://staging.d3kmgk0vkfdvym.amplifyapp.com",
    "http://localhost:5173",
    "https://inmueble-front.vercel.app",
    "https://inmueble-front-production.up.railway.app"
]
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.TokenAuthentication",
    ],
}


#Email Settings
# settings.py

# settings.py
EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
#EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS =True
EMAIL_HOST_USER = "eliteproperties453@gmail.com"            # tu cuenta
EMAIL_HOST_PASSWORD = "bxil ocdw iaus qhky"     # no tu clave normal

DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

# durante pruebas, fuerza el destinatario

EMAIL_TIMEOUT = 30

ALERTAS_AUTO_DELETE_INVALID_DEVICE = True # o False (por defecto)

# Stripe Keys
STRIPE_SECRET_KEY = config("STRIPE_SECRET_KEY", default="")
STRIPE_PUBLIC_KEY = config("STRIPE_PUBLIC_KEY", default="")
FRONTEND_SUCCESS_URL = config("FRONTEND_SUCCESS_URL", default="http://localhost:3000/success")
FRONTEND_CANCEL_URL = config("FRONTEND_CANCEL_URL", default="http://localhost:3000/cancel")
FRONTEND_BASE_URL = config("FRONTEND_BASE_URL", default="http://localhost:5173")
STRIPE_WEBHOOK_SECRET = config("STRIPE_WEBHOOK_SECRET", default="")


#pip freeze > requirements.txt PARA GENERAR LISTA DE REQUIRIMIENTOS
#pip install -r requirements.txt PARA INSTALAR LOS REQUIRIMIENTOS